---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1u7y3d5lw36h8wzlakr9dtdea0s0tawd245nvdpqjlvfs0sgdzsmsqxyzg8
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1u7y3d5lw36h8wzlakr9dtdea0s0tawd245nvdpqjlvfs0sgdzsmsqxyzg8
