# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:wwSk/cWI9sdV4ceO2jMa0O134w==,iv:igzHUc0jJbKxXAlPbl5DdO5KseJSpTHULntp5OC5Uzs=,tag:zVwL+e+wmstTtRL5u/iX+Q==,type:str]
    api-key: ENC[AES256_GCM,data:faE0UQY7M/Fj63xEcvck6FcnpKPP7DxvqU/yLa7rW/O8E+DK7w==,iv:flVghuIl+VaAqoqQWSY83TftLBWW1AgO6dQ92adNK/U=,tag:hMSTf+BJKXJrjB1mH4kSjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7y3d5lw36h8wzlakr9dtdea0s0tawd245nvdpqjlvfs0sgdzsmsqxyzg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSDZlSGhYWDkwL0t1cy9y
            UmlYUXYzelpSbDlRMjdycXd6U3RrRXRHbWxZCkF6WVNuN24yMFk5YVI0YWxlZDFw
            ZjJwQmJUSnBHQVVoRUl0eUpWQkRMQ0UKLS0tICtjejVrVDhmbUIyQ2NWaUdJWktM
            L2VOREtMREN4ZTFNejgzczlkNzVwblEK2Dvh+6Zali4n/AE45ufAkB4zdYRTbMIW
            JSszZJSsClQWqf1Cu07AR6hd1J7KEgFkXlwmWYfLqEFuMBy5VeVv+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-15T20:00:09Z"
    mac: ENC[AES256_GCM,data:XAQda/CERJdgAlGjyHhnQm+INrjUaU2I1ZeoJH/+hTvwGw51SEZE1DObxhoQo0KaINi+nyJ37JRBgQVSrWhx3T0qBx11nKlocf3RgxYvh07P84PO78J+U89GznehF1w4DS+mwcST67kyHxzWx2vRCjkQTSFmAVS77jeDahDlIKc=,iv:uFy+Wk3uRufTS60tMcXhSPxlhyJo7pN8CuTjYoTX8tE=,tag:AZxkPWn/SeMrlUM9SsKMcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
