---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 172.16.0.95-172.16.0.99
  METALLB_K8S_GATEWAY_ADDR: 172.16.0.95
  METALLB_TRAEFIK_ADDR: 172.16.0.96
